# Generated by Django 2.0 on 2018-02-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128)),
                ('released', models.DateField()),
                ('registrated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Oss',
            fields=[
                ('oss_id', models.IntegerField(primary_key=True, serialize=False)),
                ('oss_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='oss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Oss'),
        ),
        migrations.AlterUniqueTogether(
            name='info',
            unique_together={('version', 'oss')},
        ),
    ]
